### ISSUE TITLE
Are the markers in the correct position?

### ISSUE THREAD

**Issue by hwy1992129** [nghorbani/amass#32]
I visualize the markers on SMPL-X addon in Blender.
The markers are not symmetric. Some markers are in the wired positions.
![image](https://user-images.githubusercontent.com/70329303/145233006-59d72969-0a79-46f5-a278-23738d9a3a88.png)
![image](https://user-images.githubusercontent.com/70329303/145233041-d5d6c1e4-5bfe-47cd-b90e-2ad659d53271.png)
![image](https://user-images.githubusercontent.com/70329303/145233112-fd51b6f7-8b69-4f73-8c44-1800dca36caf.png)
I have one more question. Why the joints in SMPL model are not symmetric?

**Comment by nghorbani** [comment]
Hi, 
For your first question, that is just the way original mocap markers are placed on the body. Furthermore, asymmetric marker placement is a strategy to make side identification for cleaning easier.

The marker labels is not important to MoSh since it optimizes the placement anyways in stageI. Please refer to MoSh or SOMA to learn more on marker based mocap and internals of MoSh.

SMPL joints are learned during SMPL model training to be inside the mesh volume and be center of rotation.

Best,
Nima
